services:
  - type: web
    name: raft-aplikacija
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: raft-baza
          property: connectionString

databases:
  - name: raft-baza
